2 rework cambench cap fix algo
CROSSINGTUD/CamBench pull request #4
Opened 2023-07-21 11:32 UTC by schlichtig

Rework of CamBench_Cap

2023-07-24 07:43 UTC, akwick requested changes
Thanks for the extensive refactoring. I focused my review *only* on the changes.

I selected *Request changes* because of the two(?) cases where you use GCM with PKCS5Padding. Without them, I would have chosen *Approve* as these are more feedback and should not influence the evaluation results. ;)

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/basic/brokencrypto/CorrectedCrypto.java
> +        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
🔑  👍

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/basic/brokencrypto/CorrectedCrypto_meta2.yaml
> +  The KeyGenerator is used with a secure algorithm (AES).
👍

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/basic/ecbmode/CorrectedEcbMode_meta.yaml
> +  The AES algorithm is configured and initialized securely with the GCM mode of operation.
👍

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/fieldsensitivity/truepositive/brokencrypto/BrokenCrypto1.java
> +        cryptoClass.cipher2 = "AES/GCM/NoPadding";
👍  Good one!

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/interprocedural3/truepositive/brokencrypto/CorrectedCrypto.java
> +        String algoConfig = String.join("/", algorithm,"GCM","PKCS5Padding");
What was your rationale to leave the PKCS5Padding for GCM?

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/mixedsensitivities/inter2path/falsepositive/ecbmode/EcbMode1_meta.yaml
> +  A configuration for the AES cipher using the GCM mode is passed to a method in the reachable branch of a conditional
Minor revision of the sentence. 
A configuration for the AES cipher using the GCM mode. 
This configuration is passed to a method in the reachable branch of a conditional statement, where it is used to initialize a cipher object.

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/mixedsensitivities/inter2path/falsepositive/brokencrypto/BrokenCrypto1_meta1.yaml
> +  A string containing the name of a secure cipher (AES) is passed to a in the reachable branch of a
Correction of the sentence (article duplication): 
... is passed to the reachable branch of a conditional statement.

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/mixedsensitivities/inter2path/truepositive/ecbmode/EcbMode1_meta.yaml
> +    Replace the ECB mode of operation through another, secure mode, e.g. GCM mode.
mode, e.g., GCM mode.

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/mixedsensitivities/objectpath/truepositive/ecbmode/EcbMode1_meta.yaml
> +    Do not utilize the ECB mode of operation. Instead, use a more secure mode, like GCM.
, such as GCM.

like is used for comparisons and is not necessarily inclusive.

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/objectsensitivity/truepositive/ecbmode/EcbMode1_meta.yaml
> +    Do not utilize the ECB mode of operation. Instead, use a more secure mode, like GCM.
, such as GCM.

Why? See above

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/contextsensitivity/truepositive/ecbmode/EcbMode1_meta.yaml
> +    Replace the ECB mode in the configuration with another, more secure mode like GCM.
, such as GCM.

Why? Explanaiton below in one of the comments.

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/interprocedural2/truepositive/brokencrypto/CorrectedCrypto.java
> +        String algoConfig = String.join("/", algo,"GCM","PKCS5Padding");
Replace PKCS5Padding with NoPadding

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/interprocedural2/truepositive/ecbmode/EcbMode1_meta.yaml
> +    Do not utilize the ECB mode of operation. Instead, use a more secure mode, like GCM.
, such as GCM

Why? See a comment below.

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/interprocedural3/truepositive/ecbmode/EcbMode1_meta.yaml
> +    Do not utilize the ECB mode of operation. Instead, use a more secure mode, like GCM.
, such as GCM

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/mixedsensitivities/fieldobject/truepositive/ecbmode/EcbMode1_meta.yaml
> +    Do not utilize the ECB mode of operation. Instead, use a more secure mode, like GCM.
, such as GCM.

2023-07-24 07:43 UTC, akwick commented on CamBench_Cap/src/main/java/org/cambench/cap/mixedsensitivities/inter2flow/truepositive/ecbmode/EcbMode1_meta.yaml
> +    Do not utilize the ECB mode of operation. Instead, use a more secure mode, like GCM.
, such as GCM

2023-07-31 13:31 UTC, schlichtig commented on CamBench_Cap/src/main/java/org/cambench/cap/basic/brokencrypto/CorrectedCrypto.java
> +        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
Good find !!!

2023-07-31 15:08 UTC, schlichtig commented
Thank you @akwick 
I incorporated your findings!

2023-07-31 19:56 UTC, akwick approved these changes

2023-07-31 19:57 UTC, akwick commented
@schlichtig thanks for changing!

2023-08-04 12:59 UTC, merged